# Generated by Django 5.0.1 on 2024-01-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('reply', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('commentParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.comment')),
            ],
        ),
    ]
